# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kitemmodels': '@stable'
    'frameworks/ktexteditor': '@stable'
    'kdevelop/kdevelop': '@stable'

Options:
  require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
