[Desktop Entry]
Type=Service
Icon=debugger
Exec=blubb
Comment=Valgrind is a tool that helps you find memory management problems in programs. http://www.valgrind.org/
Comment[bg]=Valgrind е инструмент, който ви помага да откривате проблеми с управлението на паметта в програмите. http://www.valgrind.org/
Comment[bs]=Valgrind je alat koji vam pomaže da otkrijete probleme upravljanja memorijom u programima. http://www.valgrind.org/
Comment[ca]=El Valgrind és una eina que us ajudarà a trobar problemes en la gestió de la memòria en els programes. http://www.valgrind.org/
Comment[ca@valencia]=El Valgrind és una eina que vos ajudarà a trobar problemes en la gestió de la memòria en els programes. http://www.valgrind.org/
Comment[de]=Valgrind ist ein Werkzeug, das Ihnen hilft, Speicherverwaltungsprobleme in Programmen zu finden. http://www.valgrind.org/
Comment[en_GB]=Valgrind is a tool that helps you find memory management problems in programs. http://www.valgrind.org/
Comment[es]=Valgrind es una herramienta que le ayuda a encontrar problemas de gestión de memoria en sus programas. http://www.valgrind.org/
Comment[et]=Valgrind on tööriist, mis aitab leida programmide mäluhalduse probleeme. http://www.valgrind.org/
Comment[fi]=Valgrind on työkalu, joka auttaa sinua etsimään ohjelmista muistinhallintaongelmia. http://www.valgrind.org/
Comment[fr]=Valgrind est un outil conçu pour aider à détecter des problèmes de gestion de la mémoire dans les programmes. Pour plus de détails, veuillez consulter « http://www.valgrind.org/ ».
Comment[ga]=Uirlis é Valgrind a chabhraíonn leat fadhbanna a aimsiú a bhaineann le bainisteoireacht cuimhne i do ríomhchláir.  http://www.valgrind.org/
Comment[gl]=Valgrind é unha ferramenta que lle axuda a atopar problemas de xestión da memoria nos programas. http://www.valgrind.org/
Comment[hu]=A Valgrind egy olyan eszköz, amely segít megtalálni a memóriakezelési problémákat a programokban. http://www.valgrind.org/
Comment[it]=Valgrind è uno strumento che ti aiuta a individuare problemi di gestione della memoria nei programmi. http://www.valgrind.org/
Comment[nds]=Mit dat Warktüüch Valgrind laat sik Spiekerpleegproblemen binnen Programmen opspören. (http://www.valgrind.org/)
Comment[nl]=Valgrind is een hulpmiddel voor het vinden van problemen met geheugenbeheer in programma's. http://www.valgrind.org/
Comment[pl]=Valgrind jest narzędziem, które pomaga tobie znaleźć problemy w zarządzaniu pamięcią programu. http://www.valgrind.org/
Comment[pt]=O Valgrind é uma ferramenta que o ajuda a encontrar problemas de gestão de memória nos programas. http://www.valgrind.org/
Comment[pt_BR]=O Valgrind é uma ferramenta que o ajuda a encontrar problemas de gerenciamento de memória nos programas. http://www.valgrind.org/
Comment[sk]=Valgrind je nástroj, ktorý vám pomôže nájsť problémy v správe pamäti v programoch. http://www.valgrind.org/
Comment[sv]=Valgrind är ett verktyg som hjälper dig hitta minneshanteringsproblem i program. http://www.valgrind.org/
Comment[tr]=Valgrind programların bellek yönetim sorunları bulmanıza yardımcı olan bir araçtır. http://www.valgrind.org/
Comment[uk]=Valgrind — це інструмент, що допомагатиме вам знаходити проблеми у керуванні пам’яттю, що виникають у програмах. http://www.valgrind.org/
Comment[x-test]=xxValgrind is a tool that helps you find memory management problems in programs. http://www.valgrind.org/xx
Comment[zh_CN]=Valgrind 是一个帮助您找到程序中内存管理问题的工具。http://www.valgrind.org/
Name=Valgrind Support
Name[bg]=Поддръжка на Valgrind
Name[bs]=Valgrind podrška
Name[ca]=Implementació del valgrind
Name[ca@valencia]=Implementació del valgrind
Name[de]=Unterstützung für Valgrind
Name[en_GB]=Valgrind Support
Name[es]=Implementación de Valgrind
Name[et]=Valgrindi toetus
Name[fi]=Valgrind-tuki
Name[fr]=Prise en charge de Valgrind
Name[ga]=Tacaíocht Valgrind
Name[gl]=Integración de Valgrind
Name[hu]=Valgrind támogatás
Name[it]=Supporto per Valgrind
Name[nds]=Valgrind-Ünnerstütten
Name[nl]=Ondersteuning voor Valgrind
Name[pl]=Obsługa Valgrind
Name[pt]=Suporte para o Valgrind
Name[pt_BR]=Suporte para o Valgrind
Name[sk]=Podpora Valgrindu
Name[sv]=Valgrind-stöd
Name[tr]=Valgrind Desteği
Name[uk]=Підтримка Valgrind
Name[x-test]=xxValgrind Supportxx
Name[zh_CN]=Valgrind 支持
GenericName=Debugger Frontend
GenericName[bg]=Интерфейс на дебъгер
GenericName[bs]=Korisničko okruženje za ispravljač grešaka
GenericName[ca]=Frontal del depurador
GenericName[ca@valencia]=Frontal del depurador
GenericName[cs]=Rozhraní pro ladicí nástroj
GenericName[de]=Oberfläche für Debugger
GenericName[en_GB]=Debugger Frontend
GenericName[es]=Interfaz del depurador
GenericName[et]=Siluri kasutajaliides
GenericName[fi]=Virheenpaikantimen käyttöliittymä
GenericName[fr]=Interface du débogueur
GenericName[ga]=Comhéadan Dífhabhtóra
GenericName[gl]=Interface para o depurador
GenericName[hu]=Hibakereső előtétprogram
GenericName[it]=Interfaccia debugger
GenericName[ja]=デバッガのフロントエンド
GenericName[nds]=Fehlersöker-Böversiet
GenericName[nl]=Frontend voor debugger
GenericName[pa]=ਡੀਬੱਗਰ ਫਰੰਟਐਂਡ
GenericName[pl]=Interfejs do debuggera
GenericName[pt]=Interface do Depurador
GenericName[pt_BR]=Interface do depurador
GenericName[sk]=Rozhranie debuggera
GenericName[sv]=Gränssnitt för avlusare
GenericName[tr]=Hata Ayıklayıcı Önucu
GenericName[ug]=سازلىغۇچ ئالدى ئۇچى
GenericName[uk]=Клієнтська програма зневадника
GenericName[x-test]=xxDebugger Frontendxx
GenericName[zh_CN]=调试器前端
ServiceTypes=KDevelop/Plugin
X-KDE-Library=kdevvalgrind
X-KDevelop-Version=@KDEV_PLUGIN_VERSION@
X-KDE-PluginInfo-Name=kdevvalgrind
X-KDE-PluginInfo-Author=Harald Fernengel, Hamish Rodda
X-KDE-PluginInfo-License=GPL
X-KDevelop-Category=Global
X-KDevelop-IRequired=org.kdevelop.IExecutePlugin
X-KDevelop-Mode=GUI
